spring:
  application:
    name: load-execution-service
server:
  port: 8012

  task:
    queue:
      config:
        max-queue-size: 1000
        max-task-age-hours: 24
        task-timeout-minutes: 60
        task-history-retention-hours: 168
        shutdown-timeout-seconds: 30
